version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/crysknife"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/dist"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/gwt"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/j2cl"
    schedule:
      interval: "daily"
